server:
  port: 8080

json:
  storage:
    path: ./data/tasks.json

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat